services:
  rqt-based-env:
    container_name: rqt-based-env
    image: rqt-based-env:latest
    build:
      context: .
      dockerfile: dockerfile
    command: /sbin/init
    privileged: true
    cgroup: host
    ipc: host
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    ports:
      # Device config: SyncMCmdPort / FwdFlashQtrmPort (other devices connect IN)
      - "61001:61001"
      - "61002:61002"
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_DRIVER_CAPABILITIES=all
      - FASTDDS_DEFAULT_PROFILES_FILE=/opt/ros/fastdds-profile.xml
      - ROS_DOMAIN_ID=0
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./fastdds-profile.xml:/opt/ros/fastdds-profile.xml:ro
      - /home/trungnb/workspace/my-work:/workspace
      - ~/.docker-qtcreator/config:/root/.config/QtProject
      - ~/.docker-qtcreator/share:/root/.local/share/QtProject
      - ~/.docker-qtcreator/cache:/root/.cache/QtProject
    devices:
      - /dev/dri
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: "no"