#!/bin/bash
#
# host-audio.sh - give the container the host's sound devices and audio server.
#
# Sourced by start-qt-container*.sh. It provides:
#   HOST_AUDIO_ARGS            array of extra `docker run` arguments
#   apply_host_audio <name>    post-start steps that need a running container
#
# There are two separate problems here.
#
# 1. /dev/snd inside the container is a snapshot taken when the container was
#    created. A card plugged in afterwards - a USB capture device, say - has no
#    device nodes inside, even though /proc/asound (shared with the host) lists
#    it. Bind-mounting /dev/snd keeps the nodes in sync with the host.
#
# 2. On the host, pipewire-alsa redefines the ALSA "default" PCM to follow the
#    desktop's current default source/sink. The container has no such config, so
#    "default" falls back to raw card 0. Code calling snd_pcm_open("default",...)
#    then records from a completely different device than it does on the host -
#    typically the unconnected onboard input. Routing ALSA through the host's
#    PulseAudio/PipeWire socket restores the host's behaviour.

_host_audio_runtime="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
_host_audio_plugin=/usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_pcm_pulse.so

HOST_AUDIO_ARGS=()

# Live sound device nodes rather than a start-time snapshot.
[ -d /dev/snd ] && HOST_AUDIO_ARGS+=( -v /dev/snd:/dev/snd )

# The host's audio server. Its socket authenticates by uid, and the container
# runs as root, so the cookie has to come along too.
if [ -S "$_host_audio_runtime/pulse/native" ]; then
    HOST_AUDIO_ARGS+=(
        -v "$_host_audio_runtime/pulse/native:/run/host-pulse"
        -e PULSE_SERVER=unix:/run/host-pulse
    )
    if [ -f "$HOME/.config/pulse/cookie" ]; then
        HOST_AUDIO_ARGS+=(
            -v "$HOME/.config/pulse/cookie:/root/.config/pulse/cookie:ro"
            -e PULSE_COOKIE=/root/.config/pulse/cookie
        )
    fi
fi

# Steps that need the container to be up.
apply_host_audio() {
    local container="$1"

    docker exec "$container" test -S /run/host-pulse 2>/dev/null || {
        echo "Host audio server not shared - ALSA 'default' stays on raw card 0."
        return 0
    }

    # ALSA reaches PulseAudio/PipeWire through this plugin. The image installs
    # it (see the dockerfile); fall back to installing it live for an image
    # built before that was added.
    if ! docker exec "$container" test -e "$_host_audio_plugin" 2>/dev/null; then
        echo "Installing libasound2-plugins (ALSA -> PulseAudio bridge)..."
        docker exec "$container" bash -c \
            'apt-get update -qq && apt-get install -y -qq libasound2-plugins' >/dev/null 2>&1 || true
    fi

    if ! docker exec "$container" test -e "$_host_audio_plugin" 2>/dev/null; then
        echo "  libasound2-plugins unavailable - ALSA 'default' stays on raw card 0."
        return 0
    fi

    # What pipewire-alsa does on the host, minus the running PipeWire daemon.
    docker exec -i "$container" bash -c 'cat > /etc/asound.conf' <<'EOF'
# generated by host-audio.sh - route ALSA through the host's audio server
pcm.!default {
    type pulse
    hint.description "Default (host audio server)"
}
ctl.!default {
    type pulse
}
EOF
    echo "Audio: ALSA 'default' routed to the host audio server."
}

# Executed rather than sourced: apply the runtime part to a container that is
# already up, e.g. one started with `docker compose up`.
#
#   ./host-audio.sh [container-name]
#
if [ "${BASH_SOURCE[0]}" = "$0" ]; then
    apply_host_audio "${1:-rqt-based-env}"
fi
